//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_PersonalActivity
    {
        public Activities_PersonalActivity()
        {
            this.Progresses_PersonalProgress = new HashSet<Progresses_PersonalProgress>();
        }
    
        public System.Guid UserId { get; set; }
        public int Id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<Progresses_PersonalProgress> Progresses_PersonalProgress { get; set; }
    }
}
