//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_GroupActivity
    {
        public Company_GroupActivity()
        {
            this.Progresses_GroupProgress = new HashSet<Progresses_GroupProgress>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int GroupActivityId { get; set; }
        public int GroupActivity_Id { get; set; }
    
        public virtual Activities_GroupActivity Activities_GroupActivity { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Progresses_GroupProgress> Progresses_GroupProgress { get; set; }
    }
}
