//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.IsActive = true;
            this.GroupActivities = new HashSet<GroupActivity>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<GroupActivity> GroupActivities { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
    }
}
