//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalActivity : Activity
    {
        public PersonalActivity()
        {
            this.PersonalProgresses = new HashSet<PersonalProgress>();
        }
    
        public System.Guid UserId { get; set; }
    
        public virtual ICollection<PersonalProgress> PersonalProgresses { get; set; }
    }
}
