//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IsActive = true;
            this.GroupProgress = new HashSet<GroupProgress>();
            this.PersonalProgress = new HashSet<PersonalProgress>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<GroupProgress> GroupProgress { get; set; }
        public virtual ICollection<PersonalProgress> PersonalProgress { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
    }
}
