//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progresses_GroupProgress
    {
        public int Id { get; set; }
        public System.Guid User_Id { get; set; }
        public int Company_GroupActivity_Id { get; set; }
    
        public virtual Company_GroupActivity Company_GroupActivity { get; set; }
        public virtual Progress Progress { get; set; }
        public virtual User User { get; set; }
    }
}
