//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_GroupActivity
    {
        public Activities_GroupActivity()
        {
            this.Company_GroupActivity = new HashSet<Company_GroupActivity>();
        }
    
        public int CompanyId { get; set; }
        public int Id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<Company_GroupActivity> Company_GroupActivity { get; set; }
    }
}
