//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmployee
    {
        public CompanyEmployee()
        {
            this.IsActive = true;
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public System.Guid UserId { get; set; }
        public int EmployeeTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
