//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOClock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupActivity : Activity
    {
        public GroupActivity()
        {
            this.GroupProgresses = new HashSet<GroupProgress>();
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int CompanyId { get; set; }
    
        public virtual ICollection<GroupProgress> GroupProgresses { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
